# Generated by Django 4.2 on 2023-06-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicoAPI', '0002_user_confirm_password_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]